name: Push Official Frontend to Dockerhub

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
    update_dockerhub:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: frontend
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Print the actor's username
              run: echo "The actor is ${{ github.actor }}"
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASS }}
            - name: get latest tag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
              id: get-latest-tag
              with:
                fallback: latest
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '16.18'
            - name: Cache
              uses: actions/cache@v1
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/packagge-lock.json')}}
                restore-keys: |
                    ${{ runner.os }}-node-
            - name: Install
              run: |
                npm i -g @quasar/cli
            - name: Build official
              run: npm install -d;npm run build:public;
            - run: ls dist
            - run: docker info
            - name: Build the official Docker image
              run: |
                docker build . --tag beclab/market-official-frontend:${{ steps.get-latest-tag.outputs.tag }}
                docker push beclab/market-official-frontend:${{ steps.get-latest-tag.outputs.tag }}